# Generated by Django 5.1.6 on 2025-02-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hamburguesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ingredientes', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('client', models.CharField(max_length=30)),
            ],
        ),
    ]
